### ISSUE TITLE
500 ERROR on redirect

### ISSUE THREAD

**Issue by ghost** [DockerIt/opencart-docker#3]
http://opencart.dev/install/index.php
This page isn’t working

opencart.dev is currently unable to handle this request.
HTTP ERROR 500
docker host is ubuntu

i see nothiing in logs/apache

docker ps shows
docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
7b5c9d69ce71        opencartdocker_apache           "/opt/docker/bin/e..."   24 minutes ago      Up 24 minutes       0.0.0.0:80->80/tcp, 443/tcp                                        opencartdocker_apache_1
267768586cd0        opencartdocker_php-fpm          "docker-php-entryp..."   24 minutes ago      Up 24 minutes       9000/tcp                                                           opencartdocker_php-fpm_1
9cb5a25c7a68        mysql:latest                    "docker-entrypoint..."   24 minutes ago      Up 24 minutes       3306/tcp                                                           opencartdocker_mysql_1

php-fp shows
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "#5 /var/www/html/upload/system/engine/action.php(79): ControllerCommonFooter->index(Array)"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "#6 /var/www/html/upload/system/engine/loader.php(48): Action->execute(Object(Registry), Array)"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "#7 /..."
172.19.0.4 -  20/Aug/2017:21:29:39 +0000 "GET /install/index.php" 500
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:29:39] WARNING: [pool www] child 5 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fopen(/var/www/html/upload/system/storage/logs/error.log): failed to open stream: Permission denied in /var/www/html/upload/system/library/log.php on line 22"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/upload/system/storage/cache/d8). in /var/www/html/upload/system/storage/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:62"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "Stack trace:"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#0 /var/www/html/upload/system/storage/vendor/twig/twig/lib/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/var/www/html/u...', '<?php\n\n/* commo...')"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#1 /var/www/html/upload/system/library/template/twig.php(26): Twig_Environment->loadTemplate('common/footer.t...')"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#2 /var/www/html/upload/system/library/template.php(51): Template\Twig->render('common/footer', true)"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#3 /var/www/html/upload/system/engine/loader.php(125): Template->render('common/footer', true)"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#4 /var/www/html/upload/install/controller/common/footer.php(11): Loader->view('common/footer', Array)"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#5 /var/www/html/upload/system/engine/action.php(79): ControllerCommonFooter->index(Array)"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#6 /var/www/html/upload/system/engine/loader.php(48): Action->execute(Object(Registry), Array)"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "#7 /..."
172.19.0.4 -  20/Aug/2017:21:36:30 +0000 "GET /install/index.php" 500
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:30] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
172.19.0.4 -  20/Aug/2017:21:36:45 +0000 "GET /index.php" 302
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fopen(/var/www/html/upload/system/storage/logs/error.log): failed to open stream: Permission denied in /var/www/html/upload/system/library/log.php on line 22"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/upload/system/storage/cache/d8). in /var/www/html/upload/system/storage/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:62"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "Stack trace:"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#0 /var/www/html/upload/system/storage/vendor/twig/twig/lib/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/var/www/html/u...', '<?php\n\n/* commo...')"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#1 /var/www/html/upload/system/library/template/twig.php(26): Twig_Environment->loadTemplate('common/footer.t...')"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#2 /var/www/html/upload/system/library/template.php(51): Template\Twig->render('common/footer', true)"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#3 /var/www/html/upload/system/engine/loader.php(125): Template->render('common/footer', true)"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#4 /var/www/html/upload/install/controller/common/footer.php(11): Loader->view('common/footer', Array)"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#5 /var/www/html/upload/system/engine/action.php(79): ControllerCommonFooter->index(Array)"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#6 /var/www/html/upload/system/engine/loader.php(48): Action->execute(Object(Registry), Array)"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "#7 /..."
172.19.0.4 -  20/Aug/2017:21:36:45 +0000 "GET /install/index.php" 500
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"
[20-Aug-2017 21:36:45] WARNING: [pool www] child 6 said into stderr: "NOTICE: PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/upload/system/library/log.php on line 31"

**Comment by ghost** [comment]
nevermind... permssions issuues
